services:
  db:
    image: 'postgres:11'
    restart: always
    ports:
      - '15432:5432'
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    volumes:
      - ./dbdata:/var/lib/postgresql/data
